---
deployment:
  tasks:
    # Change DOCROOT if your site lives somewhere else
    - export DOCROOT="$HOME/public_html"
    - export REPOPATH="$HOME/repositories/EdgeKitchensAndBathrooms"

    - echo "Deploying from $REPOPATH to $DOCROOT"
    - /bin/mkdir -p "$DOCROOT"

    # Copy repo → web root
    - /usr/bin/rsync -av --delete \
      --exclude='.git' \
      --exclude='.cpanel.yml' \
      "$REPOPATH"/ "$DOCROOT"/

    # Safe perms (prevents blank page on some hosts)
    - /bin/find "$DOCROOT" -type d -exec /bin/chmod 755 {} \;
    - /bin/find "$DOCROOT" -type f -exec /bin/chmod 644 {} \;

    - echo "Deploy complete."
