---
deployment:
  tasks:
    - export DOCROOT="/home/edgekitc/public_html"
    - /bin/mkdir -p "$DOCROOT"
    # IMPORTANT: cPanel runs these tasks from the repo root.
    # So copy from "./" (not the repositories path) to your docroot.
    - /bin/rsync -av --delete \
      --exclude='.git' \
      --exclude='.cpanel.yml' \
      ./ "$DOCROOT"/
    # Optional but safe perms
    - /bin/find "$DOCROOT" -type d -exec /bin/chmod 755 {} \;
    - /bin/find "$DOCROOT" -type f -exec /bin/chmod 644 {} \;
