deployment:
  tasks:
    - export DOCROOT="/home/edgekitc/public_html"
    - /bin/mkdir -p "$DOCROOT"
    - /bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' ./ "$DOCROOT"/
    - /bin/find "$DOCROOT" -type d -exec /bin/chmod 755 {} \;
    - /bin/find "$DOCROOT" -type f -exec /bin/chmod 644 {} \;
